config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root "dashboard#index", as: "dashboard"

  resources :records
  resources :items
  resources :users
  resources :plans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :user
  has_many :plan
  has_many :item
  has_many :record, through: :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :family
  has_many :record

  default_scope { order :name }

  validates :name, presence: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :family
  belongs_to :item
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :date, :description, :value, presence: true
  validates :value, numericality: true

  scope :current_month, -> { where("date >= ? AND date <= ?", Date.today.at_beginning_of_month, Date.today.end_of_month) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  belongs_to :family
  has_many :record

  validates :firstname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    # Categories
    categories = current_user.family.record
      .current_month
      .select("records.name", "items.value")
      .joins(:item)
      .group("items.name")
      .order("sum_records_value DESC")
      .sum("records.value")
    @categories = categories.map { |k, v| { key: k , value: v }}

    # Users
    users = current_user.family.record
      .current_month
      .select("users.firstname", "items.value")
      .joins(:item)
      .group("users.firstname")
      .order("sum_records_value DESC")
      .sum("records.value")
    @users = users.map { |k, v| { key: k, value: v }}

    # Costs
    costs = current_user.family.record
      .current_month
      .select(:value, :date)
      .group(:date)
      .order("date")
      .sum("value")

    costs = costs.map { |k, v| { key: k.strftime("%F"), value: v }}

    now = Time.now
    Time.days_in_month(now.month, now.year).times do |i|
      day = i + 1
      day = "0" + day.to_s if day < 10
      date = "#{now.year}-#{now.strftime('%m')}-#{day}"
      costs << { key: date, value: 0 }
    end

    @costs = costs.uniq { |i| i[:key] }.sort_by { |i| i[:key] }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = current_user.family.item.all
  end

  def create
    @item = current_user.family.item.new(item_params)

    if @item.save
      redirect_to items_path
    else
      render 'index'
    end
  end

  def destroy
    @item = current_user.family.item.find(params[:id])

    if @item.destroy
      redirect_to items_path
    else
      render "index"
    end
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = current_user.family.plan.all
  end

  def create
    @plan = current_user.family.plan.new(plan_params)

    if @plan.save
      redirect_to plans_path
    else
      render "index"
    end
  end

  def destroy
    @plan = current_user.family.plan.find(params[:id])

    if @plan.destroy
      redirect_to plans_path
    else
      render "index"
    end
  end

  private

  def plan_params
    params.require(:plan).permit(:item_id, :value)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!

  def index
    @records = current_user.family.record.all
  end

  def create
    @record = current_user.family.record.new(record_params)

    if @record.save
      redirect_to records_path
    else
      render 'index'
    end
  end

  def destroy
    @record = current_user.family.record.find(params[:id])

    if @record.destroy
      redirect_to records_path
    else
      render "index"
    end
  end

  private

  def record_params
    params.require(:record).permit(:date, :description, :item_id, :value, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = current_user.family.user.all
  end

  def create
    @user = current_user.family.user.new(user_params)

    if @user.save
      redirect_to users_path
    else
      render "index"
    end
  end

  def destroy
    @user = current_user.family.user.find(params[:id])

    if @user.destroy
      redirect_to users_path
    else
      render "index"
    end
  end

  private

  def user_params
    params.require(:user).permit(:firstname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<script>
  function columnChart(params) {
    var h = parseInt(this.style("height"));
    var w = parseInt(this.style("width"));
    var margin = {
      top: 5,
      bottom: 20,
      left: 100,
      right: 10
    };

    var xScale = d3.scaleLinear()
      .domain([0, d3.max(params.data, function(d) {
        return d.value;
      })])
      .range([margin.left, w - margin.right]);

    var yScale = d3.scaleBand()
      .domain(params.data.map(function(entry) {
        return entry.key;
      }))
      .range([margin.top, h - margin.bottom]);

    var ColorScale = d3.scaleOrdinal(d3.schemeCategory10);

    var xAxis = d3.axisBottom()
      .scale(xScale)
      .ticks(7);

    var yAxis = d3.axisLeft()
      .scale(yScale);

    this.selectAll(".bar")
      .data(params.data)
      .enter()
      .append("rect")
      .attr("class", "bar")
      .attr("fill", function(d, i) {
        return ColorScale(i);
      })
      .attr("x", margin.left)
      .attr("y", function(d, i) {
        return yScale(d.key);
      })
      .attr("width", 0)
      .attr("height", function(d) {
        return yScale.bandwidth();
      })
      .transition()
      .duration(500)
      .delay(function(d, i) {
        return i * 200;
      })
      .attr("width", function(d) {
        return xScale(d.value) - margin.left;
      });

    this.selectAll(".bar-label")
      .data(params.data)
      .enter()
      .append("text")
      .text(function(d) {
        return d.value;
      })
      .classed("bar-label", true)
      .attr("x", function(d) {
        return xScale(d.value) - 5;
      })
      .attr("y", function(d, i) {
        return yScale(d.key);
      })
      .attr("dx", 3)
      .attr("dy", function(d) {
        return yScale.bandwidth() / 1.5;
      });

    this.append("g")
      .attr("transform", "translate(0, " + (h - margin.bottom) + ")")
      .call(xAxis);

    this.append("g")
      .attr("transform", "translate(" + margin.left + ", 0)")
      .call(yAxis);
  }

  function lineChart(params) {
    var h = parseInt(this.style("height"));
    var w = parseInt(this.style("width"));

    var margin = {
      top: 5,
      bottom: 20,
      left: 40,
      right: 10
    };

    var dateParser = d3.timeParse("%Y-%m-%d");

    var xScale = d3.scaleTime()
      .domain(d3.extent(params.data, function(d) {
        return dateParser(d.key);
      }))
      .range([margin.left, w - margin.right]);

    var yScale = d3.scaleLinear()
      .domain([0, d3.max(params.data, function(d) {
        return d.value;
      })])
      .range([h - margin.bottom, margin.top]);

    var xAxis = d3.axisBottom()
      .scale(xScale)
      .ticks(d3.timeDay, 2)
      .tickFormat(d3.timeFormat("%d-%m-%y"));

    var yAxis = d3.axisLeft()
      .scale(yScale)
      .ticks(5);

    var line = d3.line()
      .x(function(d) {
        return xScale(dateParser(d.key));
      })
      .y(function(d) {
        return yScale(d.value);
      })
      .curve(d3.curveCatmullRom);

    this.append("g")
      .classed("x axis", true)
      .attr("transform", "translate(0, " + (h - margin.bottom) + ")")
      .call(xAxis);

    this.append("g")
      .classed("y axis", true)
      .attr("transform", "translate(" + margin.left + ", 0)")
      .call(yAxis);

    // enter()
    this.selectAll(".line")
      .data([params.data])
      .enter()
      .append("path")
      .classed("line", true)
      .attr("fill", "none")
      .attr("stroke", "#d62728")
      .attr("stroke-width", "2");

    this.selectAll(".point")
      .data(params.data)
      .enter()
      .append("circle")
      .classed("point", true)
      .attr("r", 2)
      .attr("fill", "#d62728");

    // update
    this.selectAll(".line")
      .attr("d", function(d) {
        return line(d);
      });

    this.selectAll(".point")
      .attr("cx", function(d) {
        return xScale(dateParser(d.key));
      })
      .attr("cy", function(d) {
        return yScale(d.value);
      });

    // exit
    this.selectAll(".line")
      .data([params.data])
      .exit()
      .remove();

    this.selectAll(".point")
      .data(params.data)
      .exit()
      .remove();
  }

  $(function() {
    var dashboard = d3.select(".dashboard")

    // Costs
    var costs = <%= @costs.to_json.html_safe %>;

    var costsPanel = dashboard.append("div")
      .classed("row", true)
      .append("div")
      .classed("col-md-12", true)
      .append("div")
      .classed("panel panel-blue", true);

    costsPanel.append("div")
      .classed("panel-heading", true)
      .text("Расходы");

    var costsSvg = costsPanel.append("div")
      .classed("panel-body", true)
      .append("svg")
      .attr("height", "100%")
      .attr("width", "100%");

    lineChart.call(costsSvg, {
      data: costs
    });

    // Categories
    var categories = <%= @categories.to_json.html_safe %>;
    var categoriesPanel = dashboard.append("div")
      .classed("row", true)
      .append("div")
      .classed("col-md-12", true)
      .append("div")
      .classed("panel panel-blue", true);

    categoriesPanel.append("div")
    .classed("panel-heading", true)
    .text("Категории");

    var categoriesSvg = categoriesPanel.append("div")
    .classed("panel-body", true)
    .append("svg")
    .attr("height", "100%")
    .attr("width", "100%");

    columnChart.call(categoriesSvg, {
      data: categories
    });

    // Users
    var users = <%= @users.to_json.html_safe %>;
    var usersPanel = dashboard.append("div")
      .classed("row", true)
      .append("div")
      .classed("col-md-12", true)
      .append("div")
      .classed("panel panel-blue", true);

    usersPanel.append("div")
      .classed("panel-heading", true)
      .text("Семья");

    var usersSvg = usersPanel.append("div")
      .classed("panel-body", true)
      .append("svg")
      .attr("height", "100%")
      .attr("width", "100%");

    columnChart.call(usersSvg, {
      data: users
    });
  });
</script>

<style>
  .domain, .tick line {
    stroke: white;
  }
  .tick text {
    fill: white;
  }
</style>

<div class="dashboard">
</div>

app/views/items/index.html.erb
<% if defined? @item and @item.errors.any? %>
  <div class="error">
    <h2>
      <%= pluralize(@item.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="panel panel-blue">
  <div class="panel-body">

    <%= form_for :item, html: {class: "form-inline"} do |f| %>
      <div class="form-group">
        <%= f.text_field :name, type: "text", class: "form-control", placeholder: "Наименование" %>
      </div>
      <%= f.submit "Добавить", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">Категории</div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Наименование</th>
          <th>Действия</th>
        </tr>
      </thead>

      <% if @items.present? %>
        <% @items.each_with_index do |item, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= item.name %></td>
            <td>
              <a id="edit" class="btn btn-warning">Редактировать</a>
              <%= link_to "Удалить",
                item_path(item),
                method: :delete,
                data: { confirm: "Вы уверены, что хотите удалить данную запись?" },
                class: "btn btn-danger"
              %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td>Нет записей</td>
        </tr>
      <% end %>

    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mountt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-blue">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Mountt</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
                Помощь
              </a>
            </li>
            <li class="dropdown">
              <% if user_signed_in? %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                  <%= current_user.firstname %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="#">
                      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                      Настройки
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span>
                      Платежи
                    </a>
                  </li>
                  <li role="separator" class="divider"></li>
                  <li>
                    <%= link_to destroy_user_session_path, :method => :delete do %>
                      <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                      Выход
                    <% end %>
                  </li>
                </ul>
              <% else %>
                <%= link_to new_user_session_path do %>
                  <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                  Войти
                <% end %>
              <% end %>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="menu col-md-2">
          <div class="panel panel-blue panel-body">
            <ul>
              <li>
                <%= link_to dashboard_path do %>
                  <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
                  Аналитика
                <% end %>
              </li>
              <li>
                <%= link_to records_path do %>
                  <span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></span>
                  Учет
                <% end %>
              </li>
              <li>
                <%= link_to plans_path do %>
                  <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
                  План
                <% end %>
              </li>
              <li>
                <%= link_to items_path do %>
                  <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
                  Категории
                <% end %>
              </li>
              <li>
                <%= link_to users_path do %>
                  <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                  Cемья
                <% end %>
              </li>
            </ul>
          </div>
        </div>

        <div class="col-md-10">
          <% if notice %>
            <div class="alert alert-success" role="alert">
              <%= notice %>
            </div>
          <% end %>
          <% if alert %>
            <div class="alert alert-danger" role="alert">
              <%= alert %>
            </div>
          <% end %>
            <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/plans/index.html.erb
<% if defined? @plan and @plan.errors.any? %>
  <div class="error">
    <h2>
      <%= pluralize(@plan.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="panel panel-blue">
  <div class="panel-body">

    <%= form_for :plan, html: {class: "form-inline"} do |f| %>
      <div class="form-group">
        <%= f.select :item_id, current_user.family.item.map { |item| [item.name, item.id] }, {}, { class: "form-control", placeholder: "Категория" } %>
        <%= f.text_field :value, type: "text", class: "form-control", placeholder: "Сумма" %>
      </div>
      <%= f.submit "Добавить", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">План</div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Категория</th>
          <th>Сумма</th>
          <th>Действия</th>
        </tr>
      </thead>

      <% if @plans.present? %>
        <% @plans.each_with_index do |plan, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= plan.item.name %></td>
            <td><%= plan.value %></td>
            <td>
              <a id="edit" class="btn btn-warning">Редактировать</a>
              <%= link_to "Удалить",
                plan_path(plan),
                method: :delete,
                data: { confirm: "Вы уверены, что хотите удалить данную запись?" },
                class: "btn btn-danger"
              %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td>Нет записей</td>
        </tr>
      <% end %>

    </table>
  </div>
</div>

app/views/records/index.html.erb
<% if defined? @record and @record.errors.any? %>
  <div class="error">
    <h2>
      <%= pluralize(@record.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="panel panel-blue">
  <div class="panel-body">
    <%= form_for :record, html: {class: "form-inline"} do |f| %>
      <div class="form-group">
        <%= f.text_field :date, type: "text", class: "form-control", placeholder: "Дата" %>
      </div>
      <div class="form-group">
        <%= f.text_field :description, type: "text", class: "form-control", placeholder: "Описание" %>
      </div>
      <div class="form-group">
        <%= f.select :item_id, current_user.family.item.map { |item| [item.name, item.id] }, {}, { class: "form-control", placeholder: "Категория" } %>
      </div>
      <div class="form-group">
        <%= f.text_field :value, type: "number", class: "form-control", placeholder: "Значение" %>
      </div>
      <div class="form-group">
        <%= f.select :user_id, current_user.family.user.map { |user| [user.firstname, user.id] }, {}, { class: "form-control", placeholder: "Член семьи" } %>
      </div>
      <%= button_tag class: "btn btn-success" do %>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Добавить
      <% end %>
    <% end %>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">Учет</div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Дата</th>
          <th>Описание</th>
          <th>Категория</th>
          <th>Значение</th>
          <th>Член семьи</th>
          <th>Действия</th>
        </tr>
      </thead>

      <% if @records.present? %>
        <% @records.each_with_index do |record, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= record.date %></td>
            <td><%= record.description %></td>
            <td><%= record.item.name %></td>
            <td><%= record.value %> ₽</td>
            <td><%= record.user.firstname %></td>
            <td>
              <a id="edit" class="btn btn-warning">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                Редактировать
              </a>
              <%= link_to record_path(record), method: :delete,
                data: { confirm: "Вы уверены, что хотите удалить данную запись?" },
                class: "btn btn-danger" do %>
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                Удалить
              <% end %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td>Нет записей<td>
        </tr>
      <% end %>

    </table>
  </div>
</div>

app/views/users/index.html.erb
<% if defined? @user and @user.errors.any? %>
  <div class="error">
    <h2>
      <%= pluralize(@user.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @users.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="panel panel-blue">
  <div class="panel-body">
    <%= form_for :user, html: {class: "form-inline"} do |f| %>
      <div class="form-group">
        <%= f.text_field :firstname, type: "text", class: "form-control", placeholder: "Имя" %>
      </div>
      <div class="form-group">
        <%= f.text_field :email, type: "text", class: "form-control", placeholder: "Email" %>
      </div>
      <%= button_tag class: "btn btn-success" do %>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Добавить
      <% end %>
    <% end %>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">Семья</div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Имя</th>
          <th>Email</th>
          <th>Действия</th>
        </tr>
      </thead>

      <% if @users.present? %>
        <% @users.each_with_index do |user, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= user.firstname %></td>
            <td><%= user.email %></td>
            <td>
              <a id="edit" class="btn btn-warning">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                Редактировать
              </a>
              <%= link_to user_path(user), method: :delete,
                data: { confirm: "Вы уверены, что хотите удалить данного члена семьи?" },
                class: "btn btn-danger" do %>
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                Удалить
              <% end %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td>Нет членов семьи<td>
        </tr>
      <% end %>

    </table>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Войти", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Зарегистрироваться", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Забыли свой пароль?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Не получили подтверждение?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Не получили информацию по разблокировке?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>